<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[test1---Testscript execution start from here---]]>
    </line>
    <line>
      <![CDATA[test123/11/2023 14-03-59----->Testscript execution failed]]>
    </line>
  </reporter-output>
  <suite started-at="2023-11-23T14:03:32 IST" name="Suite" finished-at="2023-11-23T14:04:01 IST" duration-ms="28829">
    <groups>
    </groups>
    <test started-at="2023-11-23T14:03:32 IST" name="Test" finished-at="2023-11-23T14:04:01 IST" duration-ms="28829">
      <class name="com.hms.patientmodule.PatientBookAppointmentbasetest">
        <test-method is-config="true" signature="config_bs()[pri:0, instance:com.hms.patientmodule.PatientBookAppointmentbasetest@470734c3]" started-at="2023-11-23T14:03:32 IST" name="config_bs" finished-at="2023-11-23T14:03:32 IST" duration-ms="304" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- config_bs -->
        <test-method is-config="true" signature="config_bc()[pri:0, instance:com.hms.patientmodule.PatientBookAppointmentbasetest@470734c3]" started-at="2023-11-23T14:03:32 IST" name="config_bc" finished-at="2023-11-23T14:03:41 IST" duration-ms="8893" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- config_bc -->
        <test-method is-config="true" signature="config_bm()[pri:0, instance:com.hms.patientmodule.PatientBookAppointmentbasetest@470734c3]" started-at="2023-11-23T14:03:41 IST" name="config_bm" finished-at="2023-11-23T14:03:59 IST" duration-ms="17459" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- config_bm -->
        <test-method signature="test1()[pri:0, instance:com.hms.patientmodule.PatientBookAppointmentbasetest@470734c3]" started-at="2023-11-23T14:03:59 IST" name="test1" finished-at="2023-11-23T14:03:59 IST" duration-ms="55" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.fail(Assert.java:115)
at com.hms.patientmodule.PatientBookAppointmentbasetest.test1(PatientBookAppointmentbasetest.java:32)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[test1---Testscript execution start from here---]]>
            </line>
            <line>
              <![CDATA[test123/11/2023 14-03-59----->Testscript execution failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method is-config="true" signature="config_am()[pri:0, instance:com.hms.patientmodule.PatientBookAppointmentbasetest@470734c3]" started-at="2023-11-23T14:04:00 IST" name="config_am" finished-at="2023-11-23T14:04:00 IST" duration-ms="513" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- config_am -->
        <test-method is-config="true" signature="config_ac()[pri:0, instance:com.hms.patientmodule.PatientBookAppointmentbasetest@470734c3]" started-at="2023-11-23T14:04:00 IST" name="config_ac" finished-at="2023-11-23T14:04:01 IST" duration-ms="616" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- config_ac -->
        <test-method is-config="true" signature="config_as()[pri:0, instance:com.hms.patientmodule.PatientBookAppointmentbasetest@470734c3]" started-at="2023-11-23T14:04:01 IST" name="config_as" finished-at="2023-11-23T14:04:01 IST" duration-ms="12" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- config_as -->
      </class> <!-- com.hms.patientmodule.PatientBookAppointmentbasetest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
